In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

In [2]:
gaoxiao_df = pd.read_excel('gaoxiao.xls')
# gaoxiao_df.columns
# lis = gaoxiao_df.iloc[0]
# list(lis)
gaoxiao_df.columns = list(gaoxiao_df.iloc[0])
gaoxiao_df = gaoxiao_df[1:]

In [3]:
gaoxiao_df.head(3)

,导师编码,所在学科名称,2007-2011年的岗位等级,硕士招生人数2007,硕士招生人数2008,硕士招生人数2009,硕士招生人数2010,硕士招生人数2011,硕士招生人数合计,2007-2011纵向科研项目数量,...,申请专利数2011,申请专利数合计,获得奖励个数2007,获得奖励个数2008,获得奖励个数2009,获得奖励个数2010,获得奖励个数2011,获得奖励个数合计,获得省优硕论文篇数,获得校优硕论文篇数
1,1,学科A,一级岗,3,10,6,2,3,24,4,...,1,22,0,0,0,0,0,0,NaN,NaN
2,2,学科A,七级岗,0,0,2,3,3,8,3,...,0,3,0,0,0,0,0,0,NaN,NaN
3,3,学科A,七级岗,0,0,1,2,3,6,2,...,0,0,0,0,0,0,0,0,NaN,NaN

In [4]:
gaoxiao_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 354 entries, 1 to 354
Data columns (total 43 columns):
导师编码                   354 non-null object
所在学科名称                 354 non-null object
2007-2011年的岗位等级        344 non-null object
硕士招生人数2007             354 non-null object
硕士招生人数2008             354 non-null object
硕士招生人数2009             354 non-null object
硕士招生人数2010             354 non-null object
硕士招生人数2011             354 non-null object
硕士招生人数合计               354 non-null object
2007-2011纵向科研项目数量      354 non-null object
2007-2011纵向项目到账经费合计    354 non-null object
2007-2011横向项目数量        354 non-null object
2007-2011横向项目到账经费合计    354 non-null object
到账经费5年合计               354 non-null object
发表英文论文篇数2007           354 non-null object
发表英文论文篇数2008           354 non-null object
发表英文论文篇数2009           354 non-null object
发表英文论文篇数2010           354 non-null object
发表英文论文篇数2011           354 non-null object
发表英文论文篇数合计             354 non-null object
发表英文论文篇数年均             354 non-null object
发表英文论文篇数影响因子篇均值        354 non-null object
年均影响因子                 354 non-null object
中文期刊论文篇数2007           354 non-null object
中文期刊论文篇数2008           354 non-null object
中文期刊论文篇数2009           354 non-null object
中文期刊论文篇数2010           354 non-null object
中文期刊论文篇数2011           354 non-null object
中文期刊论文篇数合计             354 non-null object
申请专利数2007              354 non-null object
申请专利数2008              354 non-null object
申请专利数2009              354 non-null object
申请专利数2010              354 non-null object
申请专利数2011              354 non-null object
申请专利数合计                354 non-null object
获得奖励个数2007             354 non-null object
获得奖励个数2008             354 non-null object
获得奖励个数2009             354 non-null object
获得奖励个数2010             354 non-null object
获得奖励个数2011             354 non-null object
获得奖励个数合计               354 non-null object
获得省优硕论文篇数              14 non-null object
获得校优硕论文篇数              47 non-null object
dtypes: object(43)
memory usage: 119.0+ KB

由上述可以看出，获得省优硕论文和校优硕论文数据有缺失

以下内容均以岗位级别为指标

In [5]:
df_person_num = gaoxiao_df.groupby('2007-2011年的岗位等级')['硕士招生人数合计'].sum()
df_person_num

2007-2011年的岗位等级
一级岗    455
七级岗    469
三级岗    236
二级岗    239
五级岗    113
六级岗    243
四级岗    609
Name: 硕士招生人数合计, dtype: int64

In [6]:
df_research_funds = gaoxiao_df.groupby('2007-2011年的岗位等级')['到账经费5年合计'].sum()
df_research_funds

2007-2011年的岗位等级
一级岗    1393.5410
七级岗    6764.0639
三级岗    1441.8515
二级岗     891.6495
五级岗     562.3500
六级岗    3460.7785
四级岗    1973.7466
Name: 到账经费5年合计, dtype: float64

In [7]:
df_writing_num_english = gaoxiao_df.groupby('2007-2011年的岗位等级')['发表英文论文篇数合计'].sum()
df_writing_num_chinese = gaoxiao_df.groupby('2007-2011年的岗位等级')['中文期刊论文篇数合计'].sum()
print(df_writing_num_english)
print(df_writing_num_chinese)
print(df_writing_num_english + df_writing_num_chinese)

2007-2011年的岗位等级
一级岗     16
七级岗    104
三级岗     16
二级岗     19
五级岗      8
六级岗     16
四级岗     40
Name: 发表英文论文篇数合计, dtype: int64
2007-2011年的岗位等级
一级岗     95
七级岗    366
三级岗     57
二级岗     52
五级岗     49
六级岗     86
四级岗    150
Name: 中文期刊论文篇数合计, dtype: int64
2007-2011年的岗位等级
一级岗    111
七级岗    470
三级岗     73
二级岗     71
五级岗     57
六级岗    102
四级岗    190
dtype: int64

In [8]:
df_patent_num = gaoxiao_df.groupby('2007-2011年的岗位等级')['申请专利数合计'].sum()
print(df_patent_num) # 专利数

2007-2011年的岗位等级
一级岗     46
七级岗    275
三级岗     23
二级岗     14
五级岗     48
六级岗     68
四级岗     43
Name: 申请专利数合计, dtype: int64

In [9]:
df_award_num = gaoxiao_df.groupby('2007-2011年的岗位等级')['获得奖励个数合计'].sum()
print(df_award_num) # 总获奖数量

2007-2011年的岗位等级
一级岗     4
七级岗    12
三级岗     2
二级岗     0
五级岗     1
六级岗     0
四级岗     7
Name: 获得奖励个数合计, dtype: int64

In [10]:
df_paper_num_s = gaoxiao_df.groupby('2007-2011年的岗位等级')['获得省优硕论文篇数'].sum()
df_paper_num_x = gaoxiao_df.groupby('2007-2011年的岗位等级')['获得校优硕论文篇数'].sum()
print(df_paper_num_s) # 省优秀论文
print(df_paper_num_x) # 校优秀论文
print(df_paper_num_s + df_paper_num_x) # 总优秀论文

2007-2011年的岗位等级
一级岗    1
七级岗    0
三级岗    1
二级岗    0
五级岗    1
六级岗    1
四级岗    4
Name: 获得省优硕论文篇数, dtype: int64
2007-2011年的岗位等级
一级岗     9
七级岗     1
三级岗    14
二级岗     6
五级岗     2
六级岗     7
四级岗    21
Name: 获得校优硕论文篇数, dtype: int64
2007-2011年的岗位等级
一级岗    10
七级岗     1
三级岗    15
二级岗     6
五级岗     3
六级岗     8
四级岗    25
dtype: int64

In [11]:
ave_gangwei = gaoxiao_df.groupby('2007-2011年的岗位等级').count()
ave_gangwei

,导师编码,所在学科名称,硕士招生人数2007,硕士招生人数2008,硕士招生人数2009,硕士招生人数2010,硕士招生人数2011,硕士招生人数合计,2007-2011纵向科研项目数量,2007-2011纵向项目到账经费合计,...,申请专利数2011,申请专利数合计,获得奖励个数2007,获得奖励个数2008,获得奖励个数2009,获得奖励个数2010,获得奖励个数2011,获得奖励个数合计,获得省优硕论文篇数,获得校优硕论文篇数
2007-2011年的岗位等级,,,,,,,,,,,,,,,,,,,,,
一级岗,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,2,8
七级岗,183,183,183,183,183,183,183,183,183,183,...,183,183,183,183,183,183,183,183,1,1
三级岗,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,3,8
二级岗,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,0,6
五级岗,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,1,2
六级岗,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,1,5
四级岗,65,65,65,65,65,65,65,65,65,65,...,65,65,65,65,65,65,65,65,6,15

In [12]:
ave_person = gaoxiao_df.groupby('2007-2011年的岗位等级').count()

计算平均每级岗位对应的个因素的平均值

In [13]:
df_qiuhe = gaoxiao_df.groupby('2007-2011年的岗位等级').sum()

In [14]:
df1 = df_qiuhe.copy()
columns = ['硕士招生人数合计', '到账经费5年合计', '发表英文论文篇数合计', '发表英文论文篇数影响因子篇均值', '中文期刊论文篇数合计', '申请专利数合计', '获得奖励个数合计']
new_df = pd.DataFrame(df1, columns=columns)
print(new_df.head(5))
df2 = ave_gangwei.copy()
new_ave_gangwei = pd.DataFrame(df2, columns=columns)
print(new_ave_gangwei)

                 硕士招生人数合计   到账经费5年合计  发表英文论文篇数合计  发表英文论文篇数影响因子篇均值  中文期刊论文篇数合计  \
2007-2011年的岗位等级
一级岗                   455  1393.5410          16           6.4953          95
七级岗                   469  6764.0639         104          73.7583         366
三级岗                   236  1441.8515          16          11.9965          57
二级岗                   239   891.6495          19           7.6339          52
五级岗                   113   562.3500           8           8.7990          49

                 申请专利数合计  获得奖励个数合计
2007-2011年的岗位等级
一级岗                   46         4
七级岗                  275        12
三级岗                   23         2
二级岗                   14         0
五级岗                   48         1
                 硕士招生人数合计  到账经费5年合计  发表英文论文篇数合计  发表英文论文篇数影响因子篇均值  中文期刊论文篇数合计  \
2007-2011年的岗位等级
一级岗                    18        18          18               18          18
七级岗                   183       183         183              183         183
三级岗                    16        16          16               16          16
二级岗                    13        13          13               13          13
五级岗                    16        16          16               16          16
六级岗                    33        33          33               33          33
四级岗                    65        65          65               65          65

                 申请专利数合计  获得奖励个数合计
2007-2011年的岗位等级
一级岗                   18        18
七级岗                  183       183
三级岗                   16        16
二级岗                   13        13
五级岗                   16        16
六级岗                   33        33
四级岗                   65        65

In [15]:
new_df

,硕士招生人数合计,到账经费5年合计,发表英文论文篇数合计,发表英文论文篇数影响因子篇均值,中文期刊论文篇数合计,申请专利数合计,获得奖励个数合计
2007-2011年的岗位等级,,,,,,,
一级岗,455,1393.5410,16,6.4953,95,46,4
七级岗,469,6764.0639,104,73.7583,366,275,12
三级岗,236,1441.8515,16,11.9965,57,23,2
二级岗,239,891.6495,19,7.6339,52,14,0
五级岗,113,562.3500,8,8.7990,49,48,1
六级岗,243,3460.7785,16,11.4511,86,68,0
四级岗,609,1973.7466,40,42.5317,150,43,7

In [16]:
new_ave_gangwei

,硕士招生人数合计,到账经费5年合计,发表英文论文篇数合计,发表英文论文篇数影响因子篇均值,中文期刊论文篇数合计,申请专利数合计,获得奖励个数合计
2007-2011年的岗位等级,,,,,,,
一级岗,18,18,18,18,18,18,18
七级岗,183,183,183,183,183,183,183
三级岗,16,16,16,16,16,16,16
二级岗,13,13,13,13,13,13,13
五级岗,16,16,16,16,16,16,16
六级岗,33,33,33,33,33,33,33
四级岗,65,65,65,65,65,65,65

In [17]:
average = new_df/new_ave_gangwei
average

,硕士招生人数合计,到账经费5年合计,发表英文论文篇数合计,发表英文论文篇数影响因子篇均值,中文期刊论文篇数合计,申请专利数合计,获得奖励个数合计
2007-2011年的岗位等级,,,,,,,
一级岗,25.277778,77.418944,0.888889,0.360850,5.277778,2.555556,0.222222
七级岗,2.562842,36.962098,0.568306,0.403051,2.000000,1.502732,0.065574
三级岗,14.750000,90.115719,1.000000,0.749781,3.562500,1.437500,0.125000
二级岗,18.384615,68.588423,1.461538,0.587223,4.000000,1.076923,0.000000
五级岗,7.062500,35.146875,0.500000,0.549937,3.062500,3.000000,0.062500
六级岗,7.363636,104.872076,0.484848,0.347003,2.606061,2.060606,0.000000
四级岗,9.369231,30.365332,0.615385,0.654334,2.307692,0.661538,0.107692

In [18]:
index = [18, 103, 110, 123, 150, 168, 274, 324, 335, 352]
buchong = pd.DataFrame(gaoxiao_df, index=index, columns=columns)
buchong

    硕士招生人数合计 到账经费5年合计 发表英文论文篇数合计 发表英文论文篇数影响因子篇均值 中文期刊论文篇数合计 申请专利数合计 获得奖励个数合计
18        13        5          3          0.7163          2       0        0
103        6      4.8          0               0          0       0        0
110        4       10          0               0          0       0        0
123        3        2          1           3.179          0       5        0
150       14     75.6          4          1.6573          0       0        0
168       12     24.9          5          2.1842         13       2        0
274       14     81.2          1           0.503          5       6        0
324       12    116.2          1           2.121          0       0        0
335        5    61.14          0               0          1       1        0
352        5     50.8          2          2.4725          1       2        1

In [19]:
buchong.iloc(0)
average.iloc(0)

In [20]:
for i in range(len(buchong)):
    lis = []
    for j in range(7):
        variance = (buchong.iloc[i] - average.iloc[j])**2
        var_add = variance.sum()
        lis.append(var_add)
    print(lis)

[5417.154550508055, 1138.7837384230158, 7256.272636823202, 4080.024920321004, 960.4984674970314, 10017.275885359493, 662.8167039489701]
[5680.499329639165, 1052.9625199493003, 7371.6699752519535, 4241.98230579562, 940.9969722695313, 10027.672988937979, 671.5194575423546]
[5033.413418528054, 735.7680688017589, 6550.426500251952, 3659.1611673340813, 660.6794722695313, 9023.417946513737, 450.1569246192779]
[6226.150508561386, 1246.6668263514855, 7933.741932064452, 4709.025336318696, 1135.7640106445313, 10625.422469519795, 875.8403356408163]
[176.29181063027778, 1643.3082479323045, 235.86561861070325, 93.13567793639062, 1716.4432927220305, 926.0065590140398, 2085.8554218658937]
[3014.7554888058326, 378.61814282580264, 4368.1084667294535, 2046.3647409156201, 252.0559799345313, 6548.8283038737345, 174.48466720881655]
[153.50794576138904, 2117.2266504258027, 103.01187931445307, 203.73352222639093, 2182.0292441445313, 625.9479795561608, 2641.537583923895]
[1717.8153116058343, 6377.105315984272, 704.6059066894534, 2327.3508234263913, 6615.089028394531, 164.26783096222263, 7382.584837751588]
[697.8811585280553, 592.2531568236167, 942.990386501953, 246.11377810331336, 688.7066972695312, 1922.1410319682816, 968.8134131115862]
[1144.6630715280553, 205.8800735025783, 1652.4044382207035, 510.27220546869785, 261.3532875820311, 2939.772678839493, 446.18646061543205]

In [21]:
buchong.iloc[0]

硕士招生人数合计               13
到账经费5年合计                5
发表英文论文篇数合计              3
发表英文论文篇数影响因子篇均值    0.7163
中文期刊论文篇数合计              2
申请专利数合计                 0
获得奖励个数合计                0
Name: 18, dtype: object

In [22]:
a = (buchong.iloc[0] - average.iloc[0])**2

In [23]:
a.sum()

5417.154550508055